# Generated by Django 6.0.1 on 2026-02-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='parent',
            new_name='chield',
        ),
    ]
