# Generated by Django 6.0.1 on 2026-02-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_parent_person_chield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='chield',
            new_name='parent',
        ),
    ]
