# Generated by Django 6.0.1 on 2026-02-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='info',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
